version: '3.8'

services:
  bitcoin_ingestion:
    build:
      context: ./bitcoin_ingestion
    container_name: bitcoin_ingestion
    environment:
      - DB_HOST=host.docker.internal
    restart: always

  api:
    build:
      context: ./api
    container_name: api
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=host.docker.internal
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5001:3000"  # Changed the internal port to avoid conflict with API
    depends_on:
      - api
    restart: always
