version: '3.8'

services:
  bitcoin_ingestion:
    image: hemantjomraj/bitcoin_ingestion:latest
    container_name: bitcoin_ingestion
    environment:
      - DB_HOST=host.docker.internal
    restart: always

  api:
    image: hemantjomraj/api:latest
    container_name: api
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=host.docker.internal
    restart: always

  frontend:
    image: hemantjomraj/frontend:latest
    container_name: frontend
    ports:
      - "5001:3000"
    depends_on:
      - api
    restart: always